name: mhu_dart_pbschema
version: 1.0.2
repository: https://github.com/maprohu/mhu_dart_pbschema

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  mhu_dart_commons:
    path: ../mhu_dart_commons
  mhu_dart_protoc:
    path: ../mhu_dart_protoc
  mhu_dart_builder:
    path: ../mhu_dart_builder
  mhu_dart_sourcegen:
    path: ../mhu_dart_sourcegen
  mhu_dart_annotation:
    path: ../mhu_dart_annotation
  mhu_flutter_commons:
    path: ../mhu_flutter_commons

dependencies:
  protobuf: ^3.0.0
  fast_immutable_collections: ^9.1.5
  fixnum: ^1.1.0

  mhu_dart_annotation: ^1.0.0
  mhu_dart_commons: ^1.0.8
  collection: ^1.17.2
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  mhu_dart_builder: ^1.0.2
  mhu_dart_protoc: ^1.0.0
  freezed: ^2.4.1

